FROM php:7.2-fpm

# Set working directory
WORKDIR /var/www

#Set root
USER root

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    mariadb-client \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    libxrender1 \
    libqt5core5a \
    wkhtmltopdf \
    xfonts-75dpi

# fix libqt5corea
RUN strip -R .note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.11.3

# Set working directory
WORKDIR /tmp

RUN curl -L -v https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb -o out.deb
RUN dpkg -i out.deb

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /var/www

# Install extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl
RUN docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
RUN docker-php-ext-install gd

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN useradd -u 33 www-data || echo "www-data user already exists, ommiting it"; 

# Change current user to www
USER www-data

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["sh","-c","cd /var/www/congresovirtual-backend/ && composer update && php artisan config:clear && php artisan key:generate && php artisan migrate && php artisan passport:install && php artisan search:reindex && cd /var/www/ && php-fpm"]

# =======================================================
